MageSlayer/paludis-gentoo-patches

- paludis/repositories/e/ebuild/0/portage_stubs.bash
it's safe until we're cross-compiling
related to #6
> stub the EAPI7 {best,has}_version features

- paludis/repositories/e/ebuild/install_functions.bash
- paludis/repositories/e/ebuild/utils/dobin
- paludis/repositories/e/ebuild/utils/dodir
- paludis/repositories/e/ebuild/utils/dodoc
- paludis/repositories/e/ebuild/utils/doexe
- paludis/repositories/e/ebuild/utils/dohard
- paludis/repositories/e/ebuild/utils/dohtml
- paludis/repositories/e/ebuild/utils/doinfo
- paludis/repositories/e/ebuild/utils/doins
- paludis/repositories/e/ebuild/utils/dolib
- paludis/repositories/e/ebuild/utils/doman
- paludis/repositories/e/ebuild/utils/domo
- paludis/repositories/e/ebuild/utils/dosbin
- paludis/repositories/e/ebuild/utils/dosed
- paludis/repositories/e/ebuild/utils/dosym
- paludis/repositories/e/ebuild/utils/fowners
- paludis/repositories/e/ebuild/utils/fperms
- paludis/repositories/e/ebuild/utils/keepdir
Since the mentioned variables come without a slash appended in EAPI 7,
we now have to make sure that any usage actually contains a slash.
We can hence strip out the last slash from the variables (for previous
EAPIs, not affecting 7) and unconditionally use a slash now.
> repositories: fix {,E}{D,ROOT} usage in EAPI 7.

- paludis/repositories/e/e_repository_TEST_5_setup.sh
- paludis/repositories/e/e_repository_TEST_6_setup.sh
The BASH_COMP variable accepts both dotted and non-dotted version
numbers.
However, using the (deprecated) shopt values of compatXX will always set
it to a non-dotted value. Setting it to a value automatically enables
the compatXX setting.
Since ebuild.bash now goes ahead to dump all options (via shopt -p),
meddles with them (if necessary) and re-sets them via eval, BASH_COMPAT
will always end up being set to a non-dotted value.
Let's accept both values in the test cases.
> repositories: also accept non-dotted BASH_COMP values.

- paludis/repositories/e/ebuild/die_functions.bash
- paludis/repositories/e/ebuild/exheres-0/build_functions.bash
- paludis/repositories/e/ebuild/utils/unpack
User code might change `IFS` to other values, which affects variable
expansion, most notably that of `${PIPESTATUS[*]}`.
All our `assert()` implementations depend upon its expansion being
delimited with spaces, so make sure to save, reset and restore `IFS` in
each one.
Fixes: https://github.com/MageSlayer/paludis-gentoo-patches/issues/30
> repositories: save, reset and restore IFS when using bash's PIPESTATUS feature.

- paludis/repositories/e/e_repository_TEST_0_setup.sh
- paludis/repositories/e/e_repository_TEST_1_setup.sh
- paludis/repositories/e/e_repository_TEST_2_setup.sh
- paludis/repositories/e/e_repository_TEST_4_setup.sh
- paludis/repositories/e/ebuild/utils/doins
Target paths were not correctly quoted for recursive doins invocations, which lead to breakage.
A simple example would be "bar" -> "fo o", which would not have worked at all.
Fix this by quoting the files we're working with correctly, and add more extensive test cases for paths like these.
While at it, generally try to quote all unsafe components in doins.
Fixes: MageSlayer/paludis-gentoo-patches#40
This PR requires #37 to be merged first. Will undraft it as soon as that's the case.
> Fix recursive doins behavior for paths with whitespace

- doc/configuration/hooks.html.part
- doc/configuration/syncers.html.part.in
- hooks/eselect_env_update.bash.in
- hooks/find_config_updates.hook
- hooks/gnu_info_index.bash
- hooks/installable_cache_regen.bash
- hooks/news.hook.in
- hooks/update_config_protect_list.bash
- paludis/fetchers/demos/docurl
- paludis/fetchers/dowget.in
- paludis/syncers/dobzr.in
- paludis/syncers/docvs.in
- paludis/syncers/dodarcs.in
- paludis/syncers/dodummy
- paludis/syncers/dogit.in
- paludis/syncers/dohg.in
- paludis/syncers/dorsync.in
- paludis/syncers/dosvn.in
- paludis/syncers/dotar.in
`echo_functions.bash` is usually available in `PALUDIS_ECHO_FUNCTIONS_DIR`, with a fallback to `PALUDIS_EBUILD_DIR`.
Make sure that all inclusions actually use that, including the documentation.
Patch provided by @negril.
> ebuild: fix echo_functions include

- paludis/action.cc
- paludis/action.hh
- paludis/repositories/e/ebuild_id.cc
This one is a bit tricky. I'll explain it more verbosely.
<s>Usually, all states are sticky. This makes sense, since it means we can easily resume operations without having to re-execute steps that were already executed once (think of `cave resume` for instance). Re-execution is slow at best and would break things at worst, like unpacking the source tree again after a successful build.</s>
The original description above was bogus. States aren't usually sticky, as far as I can see, it's just that the `PretendAction` state is only set to `failed` if a pretend operation fails. The state starts out as `non-failed`, but having one pretend operation fail means that the `PretendAction` state can only ever stay on `failed`.
Unfortunately, this also means that we cannot execute pretend actions for …
> action: add reset() to PretendAction and reset the state for each pretend run.

- paludis/repositories/e/ebuild/ebuild.bash
Some bash versions (notably at least 5.1) reset `BASH_COMPAT` to the default value (for 5.1, that's `51`) if a compat shell option is unset, even if it was previously unset. Normally, such a sequence should be a no-op, but due to the bug, it isn't.
Work around this by saving the `${BASH_COMPAT}` value before the `eval "$(shopt -p)"` call and restore it if `${BASH_COMPAT}` does not match the original value any longer.
Just a safe bugfix, merging right away.
> ebuild: work around bash bug related to BASH_COMPAT and shopt compat* options.

- paludis/repositories/e/ebuild/utils/domo
`domo` didn't handle paths with spaces correctly.
I don't remember what package I have experienced the breakage with, but the fix is easy and actually necessary anyway.
Merging directly.
> ebuild: utils: fix files and install paths with spaces in domo.

- paludis/repositories/e/eapis/7.conf
`EAPI=7` defines a new help-dependent `--with-sysroot` default econf option, so we'll just pass that too.
> eapis: add help-dependent --with-sysroot econf option.

- paludis/environments/paludis/output_conf.cc
- vim/syntax/paludis-output-conf.vim
We started using bold variants of the standard colors when implementing `eqawarn`, but never actually defined the bold variants. Whoops.
This PR fixes this and also vim's syntax highlighting by adding support for the new qawarn format.
Merging with a merge commit, since this PR consists of two commits.
> Fix eqawarn: add bold colors, add qawarn to vim syntax highlighting

- paludis/repositories/e/e_repository_TEST_0_setup.sh
- paludis/repositories/e/eapi.cc
- paludis/repositories/e/eapi.hh
- paludis/repositories/e/eapis/0.conf
- paludis/repositories/e/eapis/7.conf
- paludis/repositories/e/eapis/exheres-0.conf
- paludis/repositories/e/eapis/paludis-1.conf
- paludis/repositories/e/ebuild.cc
- paludis/util/echo_functions.bash.in
Previous EAPIs didn't specify where `elog` and friends were supposed to output to, so they typically logged to stdout.
That naturally mixes even important package manager messages with compile output, so `EAPI 7` defined that the output shall go to `stderr`.
We'll keep the output on `stdout` for `EAPI`s prior to `7`, and output to `stderr` for anything later.
Merging with a merge commit, since this PR consists of two commits.
> Only log to stderr for EAPI=7+

- paludis/repositories/e/eapi.cc
- paludis/repositories/e/eapi.hh
- paludis/repositories/e/eapis/0.conf
- paludis/repositories/e/eapis/7.conf
- paludis/repositories/e/eapis/exheres-0.conf
- paludis/repositories/e/eapis/paludis-1.conf
- paludis/repositories/e/ebuild.cc
- paludis/repositories/e/ebuild/utils/domo
`EAPI=7` started disregarding a previous `into` call for `domo`, instead installing the provided files into a hardcoded location - `/usr/share/locales`.
The prefix (`/usr`) is replaced by whatever an `into` call specified in earlier EAPIs.
> Implement into override for domo in EAPI=7.

- paludis/repositories/e/do_install_action.cc
- paludis/repositories/e/e_stripper.cc
- paludis/repositories/e/e_stripper.hh
- paludis/repositories/e/eapi.cc
- paludis/repositories/e/eapi.hh
- paludis/repositories/e/eapis/0.conf
- paludis/repositories/e/eapis/7.conf
- paludis/repositories/e/eapis/exheres-0.conf
- paludis/repositories/e/eapis/paludis-1.conf
- paludis/repositories/e/ebuild.cc
- paludis/repositories/e/ebuild/utils/7/CMakeLists.txt
- paludis/repositories/e/ebuild/utils/7/dostrip
- paludis/repositories/e/ebuild_id.cc
- paludis/repositories/unpackaged/unpackaged_stripper.cc
- paludis/stripper.cc
- paludis/stripper.hh
- paludis/stripper_TEST.cc
`EAPI=7` introduces the concept of controllable stripping, implemented through the new `dostrip` utility.
`dostrip` works with two lists: an include list and an exclude list.
Unless a package is strip restricted, the whole image directory is added to the stripping list by default. Users can then use `dostrip -x` to exclude specific files or directories from being stripped.
Excluding a directory will also exclude all files and subdirectories within that directory.
Specific files and directories can be be re-added to the list of files to strip using an argumentless `dostrip` call.
If a package is strip-restricted, no files are stripped by default.
Merging with a merge commit, since this PR consists of multiple commits.
> EAPI=7: implement controllable stripping.

- paludis/repositories/e/ebuild/utils/doins
Just syncing up the code with my `wip/*` branches. This change unfortunately fell through the cracks in 1abe27d44e085bd997b8bd73425f93bea1584026.
> doins: add curly braces to $@ variable. (NFC)

- paludis/repositories/e/e_repository_TEST_7.cc
- paludis/repositories/e/e_repository_TEST_7_setup.sh
- python/package_id_TEST_setup.sh
- ruby/package_id_TEST.rb
- ruby/package_id_TEST_setup.sh
This is a HUGE PR, bringing a lot of new tests for `EAPI=7` and updating/fixing already existing ones.
It's a combination of @negril's and mine efforts, backported to the "old" test system that has been traditionally used in paludis. @negril actually wrote it based on something newer, which spawns tests individually in a clean environment and even seems to execute a lot faster, but for getting the `EAPI-7` (and eventually `EAPI=8`) code merged upstream, it's probably better to base it on the system that is being used for older EAPIs and keep the code compatible with C++11 (instead of using later features).
Eventually, after that code is in upstream, I'd like to switch to the "new" system he proposed.
To that effect, code that we need for the "new" system has not been removed, but only …
> EAPI=7: miscellaneous test updates.

- paludis/repositories/e/eapis/8.conf
`EAPI=8` now passes `--disable-static` by default via `econf`.
> EAPI=8: add --disable-static as default econf parameter.

- paludis/repositories/e/eapi.cc
- paludis/repositories/e/eapi.hh
- paludis/repositories/e/eapis/0.conf
- paludis/repositories/e/eapis/8.conf
- paludis/repositories/e/eapis/exheres-0.conf
- paludis/repositories/e/eapis/paludis-1.conf
- paludis/repositories/e/ebuild.cc
- paludis/repositories/e/ebuild/utils/dosym
The `dosym` utility now supports an optional parameter to automatically convert a symlink into a relative representation, which is very useful for symlinks within chroots and other scenarios.
PMS specifies that the algorithm should return a path equivalent to the following shell function (using tools from GNU coreutils 8.32):
```
dosym_relative_path() {
local link=$(realpath -m -s "/${2#/}")
local linkdir=$(dirname "${link}")
realpath -m -s --relative-to="${linkdir}" "$1"
}
```
> EAPI=8: implement -r (relative) option to dosym.

- paludis/repositories/e/eapis/8.conf
More exotic archives like these should use the `unpacker` eclass.
> EAPI=8: drop 7Zip, LHA and RAR archive support.

- paludis/repositories/e/ebuild/8/CMakeLists.txt
- paludis/repositories/e/ebuild/8/src_prepare.bash
This was never intended to be supported and Gentoo main tree ebuilds never used that functionality, but submitted patches often contained hacks like these.
This change finally and officially disallows the behavior.
> EAPI=8: disable automatic eapply options pass-through via PATCHES variable/array.

- paludis/repositories/e/eapis/8.conf
This means that ebuilds will append to them by default.
> EAPI=8: make the PROPERTIES and RESTRICT variables source-merged.

- paludis/repositories/e/e_key.cc
Previously, a more lenient fetch restriction (like `primaryuri`) overrode a stricter one if it came later in the `RESTRICT` variable/list.
That doesn't make sense, so rework the algorithm to always apply the strictest value and additionally break out early if the strictest value (`fetch`) has been found, since it can't get any stricter than that.
> repositories: improve and fix fetch restrictions.

- paludis/repositories/e/eapi.cc
- paludis/repositories/e/eapi.hh
- paludis/repositories/e/eapis/0.conf
- paludis/repositories/e/eapis/8.conf
- paludis/repositories/e/eapis/exheres-0.conf
- paludis/repositories/e/eapis/paludis-1.conf
- paludis/repositories/e/fetch_visitor.cc
- paludis/repositories/e/source_uri_finder.cc
- paludis/repositories/e/source_uri_finder.hh
- paludis/repositories/e/source_uri_finder_TEST.cc
In `EAPI=8`, each URI can be prefixed with specific strings to override mirror or fetch restrictions.
Handle that by checking if URIs start with an override string in the label handling function adding mirrors.
This isn't very elegant, but works. However, it would be better to add support for this in the depspec parsing code, add new URI override types (as... non-leaf nodes, maybe?) and modify the labels accordingly if overrides has been found, but that would be way more complicated.
> EAPI=8: implement fetch and mirror overrides.
